"""Locale dictionaries for every human-readable label in the workbook.

Sheet *names* stay English/ASCII so cross-sheet formula references are stable;
only row/header labels are localized. Excel function names are always written
in English (Excel localizes their display automatically).
"""

from __future__ import annotations

LABELS: dict[str, dict[str, str]] = {
    "tr": {
        # 01_Assumptions
        "s01.title": "01 | Varsayımlar (Kontrol Paneli)",
        "s01.macro_header": "Makroekonomik Girdiler",
        "s01.risk_free": "Risksiz Faiz Oranı (Rf)",
        "s01.erp": "Hisse Senedi Risk Primi (ERP)",
        "s01.crp": "Ülke Risk Primi (CRP)",
        "s01.tax": "Kurumlar Vergisi Oranı (T)",
        "s01.fx": "Değerleme Para Birimi Kuru (örn. EUR/TRY)",
        "s01.growth_header": "Şirkete Özgü Büyüme ve Marj Varsayımları",
        "s01.growth1": "1. Aşama Gelir Büyümesi (Yıl 1-5)",
        "s01.growth2": "2. Aşama Gelir Büyümesi (Yıl 6-10)",
        "s01.terminal_growth": "Terminal Büyüme Oranı (g)",
        "s01.ebit_margin": "Hedef FVÖK (EBIT) Marjı",
        "s01.capex_pct": "Yatırım Harcamaları / Satışlar (CapEx %)",
        "s01.nwc_pct": "Net İşletme Sermayesi / Satışlar (NWC %)",
        "s01.da_pct": "Amortisman / Satışlar (D&A %)",
        "s01.weights_header": "Değerleme Karması ve Sinyal",
        "s01.weight_dcf": "İNA (DCF) Ağırlığı",
        "s01.weight_multiples": "Çarpan Ağırlığı",
        "s01.signal_threshold": "Sinyal Eşiği (±)",
        "s01.market_header": "Piyasa Verileri",
        "s01.current_price": "Güncel Hisse Fiyatı",
        "s01.shares_out": "Dolaşımdaki Pay Adedi",
        # 02_Historical_Financials
        "s02.title": "02 | Geçmiş Finansallar",
        "s02.item": "Kalem (tam para birimi)",
        "s02.is_header": "Gelir Tablosu",
        "s02.revenue": "Hasılat",
        "s02.cogs": "Satışların Maliyeti (-)",
        "s02.gross_profit": "Brüt Kâr",
        "s02.sga": "Faaliyet Giderleri (SG&A) (-)",
        "s02.ebitda": "FAVÖK (EBITDA)",
        "s02.da": "Amortisman ve İtfa (D&A)",
        "s02.ebit": "FVÖK (EBIT)",
        "s02.net_interest": "Net Finansman Gideri",
        "s02.net_income": "Dönem Net Kârı",
        "s02.bs_header": "Bilanço",
        "s02.cash": "Nakit ve Nakit Benzerleri",
        "s02.current_assets": "Toplam Dönen Varlıklar",
        "s02.total_assets": "Toplam Varlıklar",
        "s02.st_debt": "Kısa Vadeli Finansal Borçlar",
        "s02.lt_debt": "Uzun Vadeli Finansal Borçlar",
        "s02.leases": "Kiralama Yükümlülükleri",
        "s02.total_liabilities": "Toplam Yükümlülükler",
        "s02.retained": "Geçmiş Yıl Kârları",
        "s02.equity": "Toplam Özkaynaklar",
        "s02.cf_header": "Nakit Akış Kalemleri",
        "s02.capex": "Yatırım Harcamaları (CapEx)",
        "s02.derived_header": "Türetilmiş Metrikler",
        "s02.net_debt": "Net Borç (Kiralamalar Dahil)",
        "s02.rev_growth": "Gelir Büyümesi %",
        "s02.ebit_margin": "FVÖK Marjı %",
        "s02.capex_pct": "CapEx / Satışlar %",
        # 03_WACC_Calculation
        "s03.title": "03 | AOSM (WACC) Hesaplaması",
        "s03.peer_header": "Emsal Beta Matrisi",
        "s03.col_ticker": "Sembol",
        "s03.col_price": "Fiyat",
        "s03.col_shares": "Pay Adedi",
        "s03.col_mktcap": "Piyasa Değeri",
        "s03.col_debt": "Toplam Borç",
        "s03.col_cash": "Nakit",
        "s03.col_ebitda": "FAVÖK",
        "s03.col_sales": "Satışlar",
        "s03.col_ni": "Net Kâr",
        "s03.col_beta": "Kaldıraçlı Beta",
        "s03.col_de": "Borç/Özkaynak",
        "s03.col_unlev": "Kaldıraçsız Beta",
        "s03.median": "Medyan",
        "s03.target_header": "Hedef Şirket Sermaye Yapısı ve AOSM",
        "s03.mv_equity": "Özkaynak Piyasa Değeri (E)",
        "s03.mv_debt": "Toplam Borç (D, Kiralamalar Dahil)",
        "s03.weight_e": "Özkaynak Ağırlığı E/(D+E)",
        "s03.weight_d": "Borç Ağırlığı D/(D+E)",
        "s03.target_de": "Hedef Borç/Özkaynak",
        "s03.relev_beta": "Kaldıraçlandırılmış Beta",
        "s03.ke": "Özkaynak Maliyeti (Ke)",
        "s03.rd_spread": "Borçlanma Spreadi (Rf Üzeri)",
        "s03.rd": "Borç Maliyeti (Rd)",
        "s03.wacc": "AOSM (WACC)",
        # 04_DCF_Model
        "s04.title": "04 | İndirgenmiş Nakit Akımları (İNA / DCF) Modeli",
        "s04.year": "Yıl",
        "s04.t": "Dönem (t)",
        "s04.revenue": "Hasılat",
        "s04.ebit": "FVÖK (EBIT)",
        "s04.nopat": "Vergi Sonrası Faaliyet Kârı (NOPAT)",
        "s04.da": "(+) Amortisman (D&A)",
        "s04.capex": "(-) Yatırım Harcamaları (CapEx)",
        "s04.dnwc": "(-) Net İşletme Sermayesi Değişimi (ΔNWC)",
        "s04.fcff": "Firmaya Serbest Nakit Akışı (FCFF)",
        "s04.df": "İskonto Faktörü",
        "s04.pv": "Nakit Akışının Bugünkü Değeri",
        "s04.sum_pv": "Açık Dönem Bugünkü Değer Toplamı",
        "s04.tv": "Terminal Değer (Gordon Büyüme)",
        "s04.pv_tv": "Terminal Değerin Bugünkü Değeri",
        "s04.ev": "Firma Değeri (EV)",
        "s04.net_debt": "(-) Net Borç (Kiralamalar Dahil)",
        "s04.equity_value": "Özkaynak Değeri",
        "s04.implied_price": "İNA Hedef Fiyat",
        # 05_Relative_Valuation
        "s05.title": "05 | Göreceli Değerleme (Emsal Çarpanları)",
        "s05.peer_header": "Emsal Çarpan Tablosu",
        "s05.col_ev": "Firma Değeri (EV)",
        "s05.col_ev_ebitda": "EV/FAVÖK",
        "s05.col_ev_sales": "EV/Satışlar",
        "s05.col_pe": "F/K",
        "s05.median": "Medyan",
        "s05.track_ev_ebitda": "EV/FAVÖK Yaklaşımı",
        "s05.track_ev_sales": "EV/Satışlar Yaklaşımı",
        "s05.track_pe": "F/K Yaklaşımı",
        "s05.target_metric_ebitda": "Hedef Şirket FAVÖK (Son Yıl)",
        "s05.target_metric_sales": "Hedef Şirket Satışlar (Son Yıl)",
        "s05.target_metric_ni": "Hedef Şirket Net Kâr (Son Yıl)",
        "s05.median_multiple": "Medyan Çarpan",
        "s05.implied_ev": "İma Edilen Firma Değeri",
        "s05.net_debt": "(-) Net Borç",
        "s05.implied_equity": "İma Edilen Özkaynak Değeri",
        "s05.implied_price": "İma Edilen Hisse Fiyatı",
        # 06_Valuation_Summary
        "s06.title": "06 | Değerleme Özeti",
        "s06.col_method": "Yöntem",
        "s06.col_price": "Hedef Fiyat",
        "s06.col_weight": "Ağırlık",
        "s06.method_dcf": "İNA (DCF)",
        "s06.method_ev_ebitda": "EV/FAVÖK",
        "s06.method_pe": "F/K",
        "s06.method_ev_sales": "EV/Satışlar",
        "s06.weighted_target": "Ağırlıklı Hedef Fiyat",
        "s06.current_price": "Güncel Fiyat",
        "s06.upside": "Getiri Potansiyeli %",
        "s06.signal": "Otomatik Sinyal",
        "s06.signal_buy": "AL",
        "s06.signal_hold": "TUT",
        "s06.signal_sell": "SAT",
        "s06.fx_price": "Hedef Fiyat (Sabit Para Birimi)",
    },
    "en": {
        "s01.title": "01 | Assumptions (Control Dashboard)",
        "s01.macro_header": "Macro-Economic Inputs",
        "s01.risk_free": "Risk-Free Rate (Rf)",
        "s01.erp": "Equity Risk Premium (ERP)",
        "s01.crp": "Country Risk Premium (CRP)",
        "s01.tax": "Corporate Tax Rate (T)",
        "s01.fx": "Valuation Currency FX Rate (e.g. EUR/TRY)",
        "s01.growth_header": "Company-Specific Growth & Margin Assumptions",
        "s01.growth1": "Stage 1 Revenue Growth (Years 1-5)",
        "s01.growth2": "Stage 2 Revenue Growth (Years 6-10)",
        "s01.terminal_growth": "Terminal Growth Rate (g)",
        "s01.ebit_margin": "Target EBIT Margin",
        "s01.capex_pct": "CapEx-to-Sales %",
        "s01.nwc_pct": "NWC-to-Sales %",
        "s01.da_pct": "D&A-to-Sales %",
        "s01.weights_header": "Valuation Blend & Signal",
        "s01.weight_dcf": "DCF Weight",
        "s01.weight_multiples": "Multiples Weight",
        "s01.signal_threshold": "Signal Threshold (±)",
        "s01.market_header": "Market Data",
        "s01.current_price": "Current Share Price",
        "s01.shares_out": "Shares Outstanding",
        "s02.title": "02 | Historical Financials",
        "s02.item": "Line Item (full currency units)",
        "s02.is_header": "Income Statement",
        "s02.revenue": "Revenue",
        "s02.cogs": "Cost of Goods Sold (-)",
        "s02.gross_profit": "Gross Profit",
        "s02.sga": "Operating Expenses (SG&A) (-)",
        "s02.ebitda": "EBITDA",
        "s02.da": "Depreciation & Amortization (D&A)",
        "s02.ebit": "EBIT",
        "s02.net_interest": "Net Interest Expense",
        "s02.net_income": "Net Income",
        "s02.bs_header": "Balance Sheet",
        "s02.cash": "Cash & Cash Equivalents",
        "s02.current_assets": "Total Current Assets",
        "s02.total_assets": "Total Assets",
        "s02.st_debt": "Short-Term Debt",
        "s02.lt_debt": "Long-Term Debt",
        "s02.leases": "Lease Liabilities",
        "s02.total_liabilities": "Total Liabilities",
        "s02.retained": "Retained Earnings",
        "s02.equity": "Total Equity",
        "s02.cf_header": "Cash Flow Items",
        "s02.capex": "Capital Expenditures (CapEx)",
        "s02.derived_header": "Derived Metrics",
        "s02.net_debt": "Net Debt (incl. Leases)",
        "s02.rev_growth": "Revenue Growth %",
        "s02.ebit_margin": "EBIT Margin %",
        "s02.capex_pct": "CapEx / Sales %",
        "s03.title": "03 | WACC Calculation",
        "s03.peer_header": "Peer Beta Matrix",
        "s03.col_ticker": "Ticker",
        "s03.col_price": "Price",
        "s03.col_shares": "Shares",
        "s03.col_mktcap": "Market Cap",
        "s03.col_debt": "Total Debt",
        "s03.col_cash": "Cash",
        "s03.col_ebitda": "EBITDA",
        "s03.col_sales": "Sales",
        "s03.col_ni": "Net Income",
        "s03.col_beta": "Levered Beta",
        "s03.col_de": "Debt/Equity",
        "s03.col_unlev": "Unlevered Beta",
        "s03.median": "Median",
        "s03.target_header": "Target Capital Structure & WACC",
        "s03.mv_equity": "Market Value of Equity (E)",
        "s03.mv_debt": "Total Debt (D, incl. Leases)",
        "s03.weight_e": "Equity Weight E/(D+E)",
        "s03.weight_d": "Debt Weight D/(D+E)",
        "s03.target_de": "Target Debt/Equity",
        "s03.relev_beta": "Relevered Beta",
        "s03.ke": "Cost of Equity (Ke)",
        "s03.rd_spread": "Debt Spread (over Rf)",
        "s03.rd": "Cost of Debt (Rd)",
        "s03.wacc": "WACC",
        "s04.title": "04 | Discounted Cash Flow (DCF) Model",
        "s04.year": "Year",
        "s04.t": "Period (t)",
        "s04.revenue": "Revenue",
        "s04.ebit": "EBIT",
        "s04.nopat": "NOPAT",
        "s04.da": "(+) D&A",
        "s04.capex": "(-) CapEx",
        "s04.dnwc": "(-) Change in NWC (ΔNWC)",
        "s04.fcff": "Free Cash Flow to Firm (FCFF)",
        "s04.df": "Discount Factor",
        "s04.pv": "PV of FCFF",
        "s04.sum_pv": "Sum of Explicit-Period PVs",
        "s04.tv": "Terminal Value (Gordon Growth)",
        "s04.pv_tv": "PV of Terminal Value",
        "s04.ev": "Enterprise Value (EV)",
        "s04.net_debt": "(-) Net Debt (incl. Leases)",
        "s04.equity_value": "Equity Value",
        "s04.implied_price": "DCF Target Price",
        "s05.title": "05 | Relative Valuation (Peer Multiples)",
        "s05.peer_header": "Peer Multiples Table",
        "s05.col_ev": "Enterprise Value (EV)",
        "s05.col_ev_ebitda": "EV/EBITDA",
        "s05.col_ev_sales": "EV/Sales",
        "s05.col_pe": "P/E",
        "s05.median": "Median",
        "s05.track_ev_ebitda": "EV/EBITDA Approach",
        "s05.track_ev_sales": "EV/Sales Approach",
        "s05.track_pe": "P/E Approach",
        "s05.target_metric_ebitda": "Target EBITDA (Latest Year)",
        "s05.target_metric_sales": "Target Sales (Latest Year)",
        "s05.target_metric_ni": "Target Net Income (Latest Year)",
        "s05.median_multiple": "Median Multiple",
        "s05.implied_ev": "Implied Enterprise Value",
        "s05.net_debt": "(-) Net Debt",
        "s05.implied_equity": "Implied Equity Value",
        "s05.implied_price": "Implied Share Price",
        "s06.title": "06 | Valuation Summary",
        "s06.col_method": "Method",
        "s06.col_price": "Target Price",
        "s06.col_weight": "Weight",
        "s06.method_dcf": "DCF",
        "s06.method_ev_ebitda": "EV/EBITDA",
        "s06.method_pe": "P/E",
        "s06.method_ev_sales": "EV/Sales",
        "s06.weighted_target": "Weighted Target Price",
        "s06.current_price": "Current Price",
        "s06.upside": "Upside %",
        "s06.signal": "Automated Signal",
        "s06.signal_buy": "BUY",
        "s06.signal_hold": "HOLD",
        "s06.signal_sell": "SELL",
        "s06.fx_price": "Target Price (Hard Currency)",
    },
}


def label_getter(locale: str):
    table = LABELS[locale]

    def get(key: str) -> str:
        return table[key]

    return get
